sudo: false
language: python

python:
  - '2.7'

install:
  - pip install tox

env:
  - TOX_ENV=py27-test
  - TOX_ENV=py34-test
  - TOX_ENV=py35-test
  - TOX_ENV=py36-test
  - TOX_ENV=py37-test

script:
  - tox -e $TOX_ENV
